### ISSUE TITLE
Use Navigables instead of browsing contexts

### ISSUE THREAD

**Issue by kenchris** [diekus/screen-fold#104]
https://html.spec.whatwg.org/multipage/document-sequences.html#infrastructure-for-sequences-of-documents

"Most of this standard works in the language of navigables, but certain APIs expose the existence of browsing context switches, and so some parts of the standard need to work in terms of browsing contexts."

"[Browsing contexts](https://html.spec.whatwg.org/multipage/document-sequences.html#browsing-context) are a developer-facing representation of a series of documents. They correspond 1:1 with [WindowProxy](https://html.spec.whatwg.org/multipage/nav-history-apis.html#windowproxy) objects. Each navigable can present a series of browsing contexts, with [switches](https://html.spec.whatwg.org/multipage/browsers.html#browsing-context-group-switches-due-to-cross-origin-opener-policy) between those browsing contexts occuring under certain well-defined circumstances."

**Comment by kenchris** [comment]
At least if we use browsing contexts instead of navigables, we should probably have a note explaining why that is necessary

**Comment by rakuco** [comment]
With #119 and #120, we've gotten rid of all references to browsing contexts :tada:
