### ISSUE TITLE
Internationalization checklist

### ISSUE THREAD

**Issue by darktears** [diekus/screen-fold#148]
This issue is a record of the [Devices and Sensors Working Group](https://www.w3.org/das/)'s response to the [Internationalization Checklist](https://w3c.github.io/i18n-drafts/techniques/shortchecklist) for the [Device Posture API Specification](https://www.w3.org/TR/device-posture/).

- ### If the spec or its implementation contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc)
N/A

- ### If the spec or its implementation allows content authors to produce typographically appealing text, either in its own right, or in association with graphics.
N/A

- ### If the spec or its implementation allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc.
N/A

- ### If the spec or its implementation allows searching or matching of text, including syntax and identifiers
N/A

- ### If the spec or its implementation sorts text
N/A

- ### If the spec or its implementation captures user input
N/A

- ### If the spec or its implementation deals with time in any way that will be read by humans and/or crosses time zone boundaries
N/A

- ### If the spec or its implementation allows any character encoding other than UTF-8
N/A

- ### If the spec or its implementation defines markup
N/A

- ### If the spec or its implementation deals with names, addresses, time & date formats, etc
N/A

- ### If the spec or its implementation describes a format or data that is likely to need localisation
N/A

- ### If the spec or its implementation makes any reference to or relies on any cultural norms
N/A

**Comment by aphillips** [comment]
Thanks for doing the checklist! Don't forget to [request a review](https://www.w3.org/International/review-request)!

**Comment by himorin** [comment]
closing, since issue resolved via PR.
