### ISSUE TITLE
Device posture and direction interaction

### ISSUE THREAD

**Issue by aphillips** [diekus/screen-fold#151]
(no particular section)
https://www.w3.org/TR/device-posture/

The device posture spec provides an API to report whether a device is `continuous` or `folded` (and changes between these device postures). This works with, for example, foldable devices to allow for richer experiences, such as those mentioned in the very nice explainer:

* https://github.com/w3c/device-posture/blob/gh-pages/README.md

It's unclear if any thought has been given, in the larger scope described by the explainer, to the impact of text direction or writing mode on the various APIs/properties. Some languages/cultures have variant 'page turn direction' expectations for vertical folding (see, for example, EPUB's [`page-progression-direction`](https://www.w3.org/TR/epub-33/#attrdef-spine-page-progression-direction). The device posture API isn't directly affected by this, but the group might want to include scenarios and requirements from this larger perspective (to avoid conflicts between physical positioning (`left`/`right`) vs. logical positioning (`start`/`end`).

**Comment by anssiko** [comment]
Thank you @aphillips for sharing this i18n review feedback! What references would you recommend the WG should look at for text direction and writing mode considerations?

(This feedback is related to the i18n review request: https://github.com/w3c/i18n-request/issues/233)

**Comment by xfq** [comment]
> Some languages/cultures have variant 'page turn direction' expectations for vertical folding

To give some examples, for [Chinese](https://www.w3.org/TR/clreq/#major_differences_between_horizontal_and_vertical_writing_modes), [Japanese](https://www.w3.org/TR/jlreq/#major_differences_between_vertical_writing_mode_and_horizontal_writing_mode), and [Korean](https://www.w3.org/TR/klreq/#para-diffs) books in vertical writing mode, pages are progressed from right to left, although personally I haven't found any direct impact on this API.

**Comment by darktears** [comment]
I believe it's an author/web developer issue independently of the posture of the device. Even if a foldable is used in a half-folded state like a book, text direction needs to be respected like the device was being used flat. At least this API allows developers to align the content perfectly and know about the various segments thanks to the Viewport Segments API making the experience better for users. It's an opt-in feature meaning developers need to write new code, no layout change happens automatically because of the posture of the device (at least not in Chromium based browsers). 

I'm not sure what we should do in the spec beside a note but then it's just a normal guideline like many others so probably not useful to add specifically written in this spec.

**Comment by anssiko** [comment]
@darktears you could address this i18n feedback with an informative note. Guidelines for web authors are appropriate to be included as informative content.

Maybe the right context for this is under the "folded" posture section in https://www.w3.org/TR/device-posture/#posture-types 

Feel free to amend this synthesis and include more examples as appropriate:

>NOTE
>Even if a foldable is used in a half-folded state like a book, text direction needs to be respected like the device was being used flat. For example, for [Chinese](https://www.w3.org/TR/clreq/#major_differences_between_horizontal_and_vertical_writing_modes), [Japanese](https://www.w3.org/TR/jlreq/#major_differences_between_vertical_writing_mode_and_horizontal_writing_mode), and [Korean](https://www.w3.org/TR/klreq/#para-diffs) books in vertical writing mode, pages are progressed from right to left.

Please request review from @aphillips for the PR to make sure the text does capture the right things.

@xfq the illustrations from Chinese, Japanese, and Korean books were very helpful.
