### ISSUE TITLE
Comparison to other fingerprinting surface is incorrect

### ISSUE THREAD

**Issue by pes10k** [diekus/screen-fold#153]
This issue is being filed as part of the PING review requested here https://github.com/w3cping/privacy-request/issues/136

Currently the security and privacy considerations section notes that there is some fingerprinting surface exposed here, which is correct (and appreciated). However, the exact comparison being made is incorrect or at least confusing. The given example is with # of touch points on the device. These are categorically different kinds of fingerprinting risk / surface though. # of touch points will be semi identifying but fixed (and so "typical" fingerprinting surface), while the time a "the device was just folded" signal was received will be very identifying but not fixed (and so "ephemeral fingerprinting").

Its great and appreciated to note the fingerprinting concern, but it would be ideal to correct the text here, and reference a similar ephemeral fingerprinting case (https://github.com/asankah/ephemeral-fingerprinting notes several)

**Comment by darktears** [comment]
@pes10k: I need some clarification. We do not link anything regarding the # of touch points. I kept looking and unless I'm mistaken, I couldn't find any reference to it. We link this https://www.w3.org/TR/mediaqueries-4/#descdef-media-pointer which is a media feature to describe primary type of input (not the # of fingers). The example we give is about a similar use case where 2in1 has a detachable keyboard and the primary input changes over time but also requires significant user manipulation. We can definitively add a sentence or two about the fact that it is ephemeral fingerprinting.

**Comment by pes10k** [comment]
Hi @darktears , I agree, seems i got mixed up.  I think you're exactly correct here.

For some reason my memory is that the spec said "number of touch points" or similar (which would be a mostly-consistent psuedo-identifier), but I see thats not the case.  I must have been reviewing multiple specs at the same time and mixed the up (or, maybe i just wasn't reading closely enough).

Either way, i think you're right, so I'll close out the issue.  Apologies for the goof!
