### ISSUE TITLE
Rate limiting does not seem related to privacy

### ISSUE THREAD

**Issue by pes10k** [diekus/screen-fold#154]
This issue is being filed as part of the PING review requested here https://github.com/w3cping/privacy-request/issues/136

[Section 10.4.2](https://www.w3.org/TR/device-posture/#rate-limiting-change-notifications) notes that the API is rate limited as a strategy for protecting user privacy. I do not think this is provides any privacy improvement. My understanding from the PING call is that this is legacy / cruft text, and not related to the current API. I suggest removing or reworking this subsection then

**Comment by rakuco** [comment]
I'd just add that the text is fairly recent -- it was added in #145 although it was kind of rewording and reorganizing existing content. I agree that the section doesn't look like an actual mitigation, but rather a description of how the API works.
