### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by xfq** [diekus/screen-fold#51]
The "Commit history" link in https://w3c.github.io/screen-fold/ is broken.

To fix it, we can either change our default branch to `gh-pages`, or add a [branch](https://respec.org/docs/#github) property to the ReSpec config.

**Comment by anssiko** [comment]
Let’s default to the `gh-pages` branch, since the “master/slave” terminology is considered problematic.

@xfq please reconfigure the repo.

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/screen-fold/commit/d88b2b3e3a0d603b752c6df439a1e352892fae0e

/cc @diekus @kenchris
