### ISSUE TITLE
Links from sec/priv sections back to normative mitigations?

### ISSUE THREAD

**Issue by samuelweiler** [diekus/screen-fold#53]
Section 8.2 is marked as non-normative summary of "some of the mitigation strategies specified in the normative sections of this specification."  Would you add links back to the normative text for each mitigation?

Ideally, please also split security and privacy concerns into separate sections, as [requested in the current questionnaire.](https://w3ctag.github.io/security-questionnaire/#reviews)

**Comment by anssiko** [comment]
I believe this is the informative-to-normative text mapping:

- Secure Context -> https://w3c.github.io/screen-fold/#the-screenfold-interface
- Focused Area and Visibility State -> https://w3c.github.io/screen-fold/#screen-fold-angle-change

If we want to go more specific than that with these links, would need to add dfns to the algorithm steps.

@samuelweiler does PING have a convention for annotating such informative-to-normative mapping in web specs? Need to be careful to not mix informative and normative text, maybe wrap in a note?

**Comment by darktears** [comment]
With #138 and #132 we did
- Split the security and privacy sections
- Make the mitigations strategies normative
- Linked each of the mitigations to the respective part in the spec that define them.
- Removed the focused area mitigation. It doesn't seem relevant at the moment provided that the API is less sensible that where it was borrowed from.
