### ISSUE TITLE
Suggestion: Rename to Device Posture API

### ISSUE THREAD

**Issue by kenchris** [diekus/screen-fold#54]
After having a chat with a bunch of folks, I am suggesting that we rename the spec to Device Posture API and move angle (animation) use-cases elsewhere.

This would fix #45 so we can move on.

Also we have heard that there is interest in postures that don't solely depend on the angle but also on other things like primary input type, so handles cases like table top:

![image](https://user-images.githubusercontent.com/1101339/108335950-cd387700-71d3-11eb-9c1a-0bbd57c752c6.png)

![image](https://user-images.githubusercontent.com/1101339/108335960-d0cbfe00-71d3-11eb-82f3-c607a1f41943.png)

Also, it is expected that devices will be release with at least two folds which means the user needs to know where the fold is, so it might make more sense if this was part of Window Segments API.

**Comment by anssiko** [comment]
(We discussed this rename proposal briefly at the Second Screen WG/CG virtual meeting, with a general support from that group: https://www.w3.org/2021/02/24-webscreens-minutes.html#t01)

While being aware of the bike-shedding potential here, I'd ask this group owning the spec for feedback on the proposed rename before advancing.

From a technical point of view, the new API is a subset of the old API, so no concerns from the Charter scope perspective regarding rename, as long as descriptive, concise (and not offensive!).

The most involved part is the rename of the so-called shortname (as in `w3.org/TR/shortname`) for which we'd need @xfq assistance for setting up the redirects. We've done this before for e.g. Wake Lock API to Screen Wake Lock API, so I'm suggesting we make `screen-fold` shortname redirect to the proposed `device-posture` shortname, unless we see a future where both would coexist.

The Chairs will help out with the logistics of the rename once everyone's happy. Heads up @reillyeon.

**Comment by torgo** [comment]
Notionally I think it's OK to rename the API, however I'm concerned that it makes it less clear what it's for. If the API is primarily to enable developers to make better UX on screens that fold then having the word "fold" in the API name could be a good thing. "Posture" is a new concept which the API introduces which is not going to be immediately understood.

**Comment by kenchris** [comment]
It's more generic and covers additional use-cases that might not involve a fold. I am not sure "posture" is less understood than "fold" - we have been talking about laptop postures and 2 in 1's for a long time.

**Comment by lauramorinigo** [comment]
At first, seems fine for me, I think @torgo refers to how "Posture" can mislead to be interpreted as the posture of any device (including not folding). Anyway, as the new implementation will cover other cases, we can go back to fold (if it's necessary) into a separate spec within the angle in order to advance with #45 .
