### ISSUE TITLE
[admin] Enable auto-publish

### ISSUE THREAD

**Issue by anssiko** [diekus/screen-fold#55]
@xfq completed [renaming main branches](https://lists.w3.org/Archives/Public/public-device-apis/2021Feb/0004.html) of W3C GitHub repositories for this group.

For this repo we've now defaulted to `gh-pages`.

Do we want to use `main` for the source and deploy to `gh-pages` similarly to other spec repos?

Regardless, I think `master` branch is now stale and can be deleted, @xfq? 

@kenchris for preference.

**Comment by anssiko** [comment]
I forgot we're using ReSpec for this spec with no build step.

@xfq what is the latest repo organization convention for ReSpec-based specs?

**Comment by reillyeon** [comment]
My understanding is that [Spec Prod](https://github.com/w3c/spec-prod) can handle compilation for both Bikeshed and ReSpec specifications. Even though ReSpec can render in the browser on load it is a better experience for it to be pre-renderer and served as static HTML.

**Comment by anssiko** [comment]
@reillyeon thanks for the reminder. Perhaps we should try Spec Prod here.

@xfq is probably familiar and can help configure.

@kenchris thoughts?

**Comment by xfq** [comment]
I haven't tried Spec Prod, and I think it is still in the experimental stage, but if you think it's worth a try, I can try it.

Some working groups have developed their own actions. See https://github.com/w3c/aria-practices/blob/master/.github/workflows/deploy.yml for an example.

**Comment by anssiko** [comment]
@xfq per https://lists.w3.org/Archives/Public/public-device-apis/2021May/0008.html we should now enable auto-publish for this spec.

**Comment by xfq** [comment]
@anssiko I have enabled auto-publish in https://github.com/w3c/device-posture/pull/72

**Comment by anssiko** [comment]
Much thanks, I did not notice that you did it already. Closing this issue.
