### ISSUE TITLE
Drop ScreenFold.angle from the Screen Fold API?

### ISSUE THREAD

**Issue by anssiko** [diekus/screen-fold#56]
Some editors and implementers of the Screen Fold API attended the Second Screen WG/CG Virtual meeting to discuss this API. During that meeting that group made the following resolution for DAS WG consideration:

>RESOLUTION: Drop ScreenFold.angle from the Screen Fold API first version (for DAS WG consideration)

https://www.w3.org/2021/02/24-webscreens-minutes.html#r01

This recommendation was primarily motivated by the following observations:
- need to focus on the most valuable use cases first,
- implementability considerations,
- privacy and security considerations,
- currently unresolved performance implications of exposing an angle in a CSS media query

I'd like to solicit feedback on this issue whether there are any concerns in scope-limiting the first version of this spec as proposed.

Hearing no concerns, I'd give the editors a mandate to start crafting a PR to remove the `angle` related API surface from the spec and align the prose with this change.

Once this spec update is complete, I suggest the group aims to publish an updated Working Draft (maybe by the end of Q1 to have a milestone) to inform the broader community of this development.

**Comment by anssiko** [comment]
I'm seeing support signals for this proposal in https://github.com/w3c/screen-fold/issues/45 and https://github.com/w3c/screen-fold/issues/54 in addition to the support signals from the [last week's meeting](https://www.w3.org/2021/02/24-webscreens-minutes.html#r01).

@kenchris feel free to submit a PR that'll carve out `ScreenFold.angle` for now, to be reviewed within the group. We can then separately work out the rename and publication as an updated Working Draft.

**Comment by darktears** [comment]
I'll do the spec changes...
