### ISSUE TITLE
Definition for "posture" missing

### ISSUE THREAD

**Issue by anssiko** [diekus/screen-fold#59]
The spec currently lacks a "posture" definition. Given this term can mean many things, we should explicitly define this term in the context of this specification.

The spec has definitions for "current posture" and "posture mode".

**Comment by lauramorinigo** [comment]
We can define posture as the following: "the physical position in which a device holds regarding its hinges." Anyway if we will associate posture regarding other devices like keyboard we should clarify that but I dont see a specific case scenario.

**Comment by LaszloGombos** [comment]
"the physical position in which a device holds regarding its hinges." - perhaps we should make this more generic and remove "hinges" from the definition (so that we can consider for example device orientation in combination of angle as well).
