### ISSUE TITLE
Rename "posture modes" to "posture types"

### ISSUE THREAD

**Issue by beaufortfrancois** [diekus/screen-fold#64]
As the DevicePosture interface has now a member called `type`, we may want to rename [posture modes](https://w3c.github.io/device-posture/#posture-modes) to "posture types" for consistency.
What do you folks think about it?

```idl
interface DevicePosture : EventTarget {
  readonly attribute DevicePostureType type;
  ...
};
```

**Comment by anssiko** [comment]
I think this was addressed by https://github.com/w3c/device-posture/pull/65/ (thanks @beaufortfrancois for that PR!).

**Comment by beaufortfrancois** [comment]
It was not addressed by #65. This issue is about renaming the "posture modes" in https://w3c.github.io/device-posture/#posture-modes to "posture types".

**Comment by anssiko** [comment]
Sorry for being trigger-happy, reopened.

**Comment by darktears** [comment]
I don't have a strong preference but if we were to be consistent, we should use "modes" in my opinion. Samsung and other folks have been using terms like "tent mode" or "flex mode" and I regularly hear people saying "being used as laptop mode".

**Comment by kenchris** [comment]
I think it should be Type as it's an enum. Would be consistent with Orientation lock spec
