### ISSUE TITLE
Move the posture object out of the Screen interface.

### ISSUE THREAD

**Issue by darktears** [diekus/screen-fold#67]
Now that the specification only covers the posture it seems weird to have the main entry point of the API to be in the `Screen` interface. 

I strongly think we should move it to another place like `window` or `window.navigator`. The thinking is that there is only a single posture at a given time and it's not dependent on the screen.

What does sound best to you folks?

- `window.navigator.posture`

- `window.posture` which is basically `posture`

I strongly think that it we land into a generic object like `navigator` or `window` we should rename the entry point from `posture` to `device_posture`.

**Comment by darktears** [comment]
@anssiko @kenchris @beaufortfrancois @lauramorinigo

**Comment by kenchris** [comment]
Never `device_posture` then it should be `devicePosture`. Putting it on just `window` and it should just be the class itself I think, like we have `window.Accelerator`. Looking at DeviceMotion etc, they only have global event handlers which I find a bit weird\

```js
ondevicemotion = () => {}
addEventListener("devicemotion", () => {});
```

But I see that these are actually quite common. But I guess we want an object like Generic Sensors, so then it makes sense to either attach it somewhere that requires you to write the name (you don't need to write `window`), or we make a constructable object.

`.hid`, `.locks`, `.bluetooth`, etc are on `navigator`.

**Comment by lauramorinigo** [comment]
I'd rather go for window.devicePosture as it makes more sense, renaming posture to devicePosture will also clarify its meaning.

**Comment by darktears** [comment]
window.devicePosture is fine by me, I can make the change.

**Comment by beaufortfrancois** [comment]
I'd love to hear from experts what makes a thing go on the `window` object rather than `window.navigator`.

**Comment by beaufortfrancois** [comment]
The spec is not really helping there

> The `navigator` attribute of the Window interface must return an instance of the Navigator interface, which represents the identity and state of the user agent (the client), and allows web pages to register themselves as potential protocol handlers.

Source: https://html.spec.whatwg.org/multipage/system-state.html#the-navigator-object

**Comment by beaufortfrancois** [comment]
The "8.9 System state and capabilities" title however suggest `devicePosture` should be under `navigator`.

**Comment by beaufortfrancois** [comment]
I'd tend to vote for `navigator.devicePosture` then.

**Comment by anssiko** [comment]
`navigator.devicePosture` would follow the established convention.

**Comment by darktears** [comment]
I've uploaded a PR to move the entry point to `navigator.devicePosture`
