### ISSUE TITLE
We need to add more examples in the explainer

### ISSUE THREAD

**Issue by darktears** [diekus/screen-fold#79]
We need to add more demos/examples in the explainer to explain the type of UX changes that a posture change will trigger.

**Comment by lauramorinigo** [comment]
Hi, we've been working during the past year on a codelab that shows up how to use the Device Posture API. It's a web camera that uses WEB RTC and it changes the layout when the device is folded. We've been receiving some feedback about it. Here is the [code](https://glitch.com/edit/#!/device-posture-example), and [live site](https://glitch.com/edit/#!/device-posture-example).
Here is a [video demo](https://www.youtube.com/watch?v=f9Bwc_Hqfcc&t=1s).

Let me know if this would be helpful.
In this case its specific to "laptop mode". I'm also working on the integration between viewport-segment API to support other postures.

**Comment by darktears** [comment]
I have linked the demos repo in the README.md with this [commit](https://github.com/w3c/device-posture/commit/7b461bcecffb14d2a11050f8a18d0029e55b6b72)
