### ISSUE TITLE
logos are preventing auto-publish 

### ISSUE THREAD

**Issue by marcoscaceres** [diekus/screen-fold#90]
I love the logos, but they are preventing us from auto-publishing the spec. We (W3C) generally only add additional logos if we are working with other another standards organization.

**Comment by marcoscaceres** [comment]
Actually, it's working now. But they are showing up like this:

<img width="870" alt="Screen Shot 2021-07-08 at 1 32 52 pm" src="https://user-images.githubusercontent.com/870154/124858278-16595e00-dff1-11eb-82f1-2e0687dc2422.png">

I think we should probably just use one of the DAS logos (maybe just the WG one?).

**Comment by lauramorinigo** [comment]
For future reference if we have the same problem I'd rather stick to the WG one.

**Comment by anssiko** [comment]
Proposal: the amazing custom logos could move to the introduction section and we’d pass the publication check. I might also want to borrow the DAS logo for the WG homepage with @diekus permission.

**Comment by marcoscaceres** [comment]
Tbh, although they look nice, it makes the spec inconsistent with other W3C specs: Generally, we reserve multiple logos for when it’s a joint deliverable with a different organization. 

It might be better to only show these logos on the README and places like that?

**Comment by anssiko** [comment]
@diekus, PTAL https://www.w3.org/das/ with credits "DAS WG logo by [diekus](https://github.com/diekus)" 🕺

**Comment by diekus** [comment]
Hola! Sorry been swamped with stuff! Yes we can remove and also use the DAS logo on the website.
