### ISSUE TITLE
Naming of this spec

### ISSUE THREAD

**Issue by xfq** [diekus/screen-fold#93]
As @nicjansma mentioned in the [AC review of the WG charter](https://www.w3.org/2002/09/wbs/33280/das2021/results) (W3C member-only link), "device posture" is already a well-established term of art that does not relate to the physical orientation or configuration of a device (foldable or otherwise). See, e.g.,

* https://help.zscaler.com/z-app/about-device-posture
* https://techdocs.f5.com/en-us/bigip-15-0-0/big-ip-access-policy-manager-per-request-policies/implementing-device-posture-checks/overview-device-posture-checks.html
* https://developers.cloudflare.com/cloudflare-one/identity/devices
* https://www.oreilly.com/library/view/cisco-ise-for/9780133103632/ch15.html
* https://www.cisco.com/en/US/docs/net_mgmt/cisco_secure_access_control_server_for_windows/4.0/user/guide/nac.html
* https://learn.akamai.com/en-us/webhelp/enterprise-application-access/eaa-device-posture-guide/GUID-4E5EB1C2-1190-4F21-8EE3-E09642B97D00.html

Should we change the spec name (again)?

/cc @diekus @kenchris

**Comment by kenchris** [comment]
It is also the term we have used for years to describe hardware devices like laptops and now foldables.

e.g. 

* https://www.windowscentral.com/surface-duo-postures 
* https://docs.microsoft.com/en-us/dual-screen/design/postures
* https://developer.android.com/guide/topics/ui/foldables#:~:text=class%20to%20retrieve-,device%20postures,-.%20You%20can%20check

**Comment by diekus** [comment]
+1. Thinking about the definition of the word "posture" I think it is clear and straightforward to stating what the API does. From the links above "device posture" seems to relate to security of a client in a network environment. I do not think it would be a source of confusion as they are different scopes and the users of either "device posture" are unlikely to be the same.

**Comment by kaduk** [comment]
> Thinking about the definition of the word "posture" I think it is clear and straightforward to stating what the API does. From the links above "device posture" seems to relate to security of a client in a network environment. I do not think it would be a source of confusion as they are different scopes and the users of either "device posture" are unlikely to be the same.

Whether or not it's a source of confusion depends on the context available to the reader who is trying to figure out what it means.  If the context is just "the W3C API" for device posture, I would posit that it's still somewhat ambiguous.

Yes, "device posture" is not a very intuitive phrase for "the software installed and running on a device, and other contextual information about its health", but neither does it seem a particularly intuitive phrase for "the state of the external (orientation) and internal (fold angles) degrees of freedom of a device with multiple possible physical orientations".

**Comment by plehegar** [comment]
Given that this API is about giving information position in which someone holds their device, I believe using "Device Posture" seems appropriate. Looking at the links provided in the original, those seem to be about state of the OS.

**Comment by chris480** [comment]
+1 for device posture. I think as this evolves to incorporate more complex orientations (asymmetric displays) the term will be reasonable enough. Otherwise maybe we could draw from origami terms? Device Plane perhaps?
